########################################################################
#	PGADMIN
########################################################################

FROM dpage/pgadmin4:6.12
USER root 
RUN mkdir -p /usr/src/storage && chown -R 5050:5050 /usr/src/storage
USER pgadmin 