{
 "title": "PostegreSQL Example",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "One day production trend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT \n\tDATE_TRUNC('minute', timestamp) AS time,\n\tROUND(AVG(goodPieces)) AS GoodPieces, \n\tROUND(AVG(badPieces))  AS BadPieces\nFROM production\nWHERE $__timeFilter(timestamp)\nGROUP BY time\nORDER BY time DESC\n\n"
    }
   ]
  },
  {
   "title": "Machine speed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  DATE_TRUNC('minute', timestamp) AS time,\n  ROUND(MachineSpeed) AS MachineSpeed\nFROM production\nWHERE $__timeFilter(timestamp) and MachineSpeed IS NOT NULL"
    }
   ]
  },
  {
   "title": "Good Pieces",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "pcs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  goodpieces\nFROM production\nWHERE\n  $__timeFilter(timestamp) and goodpieces IS NOT NULL"
    }
   ]
  },
  {
   "title": "Machine Speed",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 17, "x": 7, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  machinespeed\nFROM production\nWHERE\n  $__timeFilter(timestamp)"
    }
   ]
  },
  {
   "title": "Bad Pieces",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "pcs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  badpieces\nFROM production\nWHERE\n  $__timeFilter(timestamp) and badpieces IS NOT NULL"
    }
   ]
  }
 ]
}